//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


	public class rato : MonoBehaviour
	{

	//int id;

		void Star(){

		}

		void Update(){

		}

	void OnCollisionEnter2D(Collision2D col){
		if(col.gameObject.name == "Sofia"){
			Debug.Log ("rato empurra");
			;

		}
	}
	}


